AllCops:
  RunRailsCops: true
  Exclude:
    - bin/**/*
    - tmp/**/*
    - vendor/**/*
    - db/schema.rb

Documentation:
  Enabled: false

LineLength:
  Max: 115

Metrics/AbcSize:
  Enabled: false
